### ISSUE TITLE
Unable to update primary IP on NIC

### ISSUE THREAD

**Issue by Sebi94nbg** [profitbricks/profitbricks-cli#43]
Following command should update the primary IP on the NIC, but it just returns a debug message and does nothing:
`profitbricks nic update --datacenterid "545aa6cb-d4e4-4081-a3e3-2b16041be281" --serverid "2711e1e5-2042-432c-9279-535893d00f61" -i "7f95742c-e93c-4c4a-8c88-c10f9e74eb06" --ip "172.21.1.12"`
This command returns following and does not change anything in the DCD:
> DA DA

Waiting for the fix. Thanks!

**Comment by jasminSPC** [comment]
This issue was reported here https://github.com/profitbricks/profitbricks-cli/issues/39 and it has been fixed with version 1.2.5. It seems to me that you need to update instance of your CLI

**Comment by Sebi94nbg** [comment]
I'm already on the latest version, as the update command means, but it's still not working.
```
# npm install -g profitbricks-cli@latest
loadDep:libprofitbricks → ▐ ╢██████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:tunnel-agent → re ▐ ╢████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
loadDep:sntp → 304        ▀ ╢█████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"3.5.3"})
WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"3.5.3"})
/usr/bin/profitbricks -> /usr/lib/node_modules/profitbricks-cli/profitbricks
/usr/lib
└── profitbricks-cli@1.2.5
```

```
# profitbricks -V
1.2.1
```

```
# profitbricks nic update --datacenterid "545aa6cb-d4e4-4081-a3e3-2b16041be281" --serverid "2711e1e5-2042-432c-9279-535893d00f61" -i "7f95742c-e93c-4c4a-8c88-c10f9e74eb06" --ip "10.40.1.39"
DA DA
```

**Comment by jasminSPC** [comment]
The latest version is printing the version number correctly.

```Last login: Mon Mar 14 12:21:12 on ttys006

```Jasmins-MBP:~ jasmin$ profitbricks -V

```1.2.5

```Jasmins-MBP:~ jasmin$


Would you try removing the previous version and try reinstalling the CLI

Thanks





On Mon, Mar 14, 2016 at 12:29 PM, TS3tools <notifications@github.com> wrote:

> I'm already on the latest version, as the update command means, but it's
> still not working.
>
> # npm install -g profitbricks-cli@latest
> loadDep:libprofitbricks → ▐ ╢██████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
> loadDep:tunnel-agent → re ▐ ╢████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
> loadDep:sntp → 304        ▀ ╢█████████████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
> WARN engine hoek@2.16.3: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"3.5.3"})
> WARN engine boom@2.10.1: wanted: {"node":">=0.10.40"} (current: {"node":"0.10.25","npm":"3.5.3"})
> /usr/bin/profitbricks -> /usr/lib/node_modules/profitbricks-cli/profitbricks
> /usr/lib
> └── profitbricks-cli@1.2.5
>
> # profitbricks -V
> 1.2.1
>
> # profitbricks nic update --datacenterid "545aa6cb-d4e4-4081-a3e3-2b16041be281" --serverid "2711e1e5-2042-432c-9279-535893d00f61" -i "7f95742c-e93c-4c4a-8c88-c10f9e74eb06" --ip "10.40.1.39"
> DA DA
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/profitbricks/profitbricks-cli/issues/43#issuecomment-196268784>
> .
>



-- 
Jasmin Gacić

**Comment by Sebi94nbg** [comment]
Thanks, 1.2.5 solved it.

I had to fully remove the Profitbricks CLI, delete the binary and install it again to get the correct version.
